resources:
  - name: RemoteFile_1
    type: RemoteFile
    configuration:
      source: s_artifactory
      fileLocation: example-repo-local/setup/help # optional
      fileName: something.txt # optional
	  fileDateTime: 19/12/19 # optional


pipelines:
  - name: pipelines_1
    steps:
      - name: REFILE_1
        type: PowerShell
        configuration:
          nodePool: win_2019
          integrations:
            - name: s_artifactory
          outputResources:
            - name: RemoteFile_1
        execution:
          onExecute:
            - write-output "executing step..."
            - jfrog rt dl example-repo-local/setup/test.sh
