resources:
  - name: FileSpec_0007
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-local/setup/"
      recursive: false
      archiveEntries: "#/artifactory"

pipelines:
  - name: pipelines_FLSPEC_0007
    steps:
      - name: step_FLSPEC_0007
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: FileSpec_0007
        execution:
          onExecute:
            - write-output "executing step..."
