resources:
  - name: FileSpec_0013
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-local/setup/"
      recursive: false
      limit: 1@3
      sortBy:
        - created
      sortOrder: invalid
      target: 'C:\Users\pipelines\Desktop\'

pipelines:

  - name: pipelines_FLSPEC_0013
    steps:
      - name: step_FLSPEC_0013
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: FileSpec_0013
        execution:
          onExecute:
            - write-output "executing step..."
