resources:
  - name: FileSpec_2
    type: FileSpec
    configuration:
      sourceArtifactory: myArtifactory
      pattern: "test-local/setup/"
      recursive: false
      limit: 1@3
      sortBy:
        - created
      sortOrder: invalid
      target: 'C:\Users\pipelines\Desktop\'

pipelines:

  - name: pipelines_FileSpec_2
    steps:
      - name: step_FileSpec_2
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: FileSpec_2
        execution:
          onExecute:
            - write-output "executing step..."
