resources:
  - name: FileSpec_0010
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      pattern: "test-local/setup/"
      recursive: false
	  buildName: pipelines_api
      buildNumber: 1@3

pipelines:
  - name: pipelines_FLSPEC_0010
    steps:
      - name: step_FLSPEC_0010
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: FileSpec_0010
        execution:
          onExecute:
            - write-output "executing step..."
