resources:
  - name: FileSpec_1
    type: FileSpec
    configuration:
      sourceArtifactory: myArtifactory
      pattern: "test-local/setup/"
      recursive: false
      offset: 1@3

pipelines:
  - name: pipe_FileSpec_1
    steps:
      - name: step_FileSpec_1
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: FileSpec_1
        execution:
          onExecute:
            - write-output "executing step..."
