resources:
  - name: FileSpec_3
    type: FileSpec
    configuration:
      sourceArtifactory: myArtifactory
      pattern: "test-local/setup/"
      recursive: false
	buildName: pipelines_api
      	buildNumber: 1@3

pipelines:
  - name: pipelines_FileSpec_3
    steps:
      - name: step_FileSpec_3
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: FileSpec_3
        execution:
          onExecute:
            - write-output "executing step..."
