resources:
  - name: FileSpec_4
    type: FileSpec
    configuration:
      sourceArtifactory: myArtifactory
      pattern: "test-local/setup/"
      recursive: false
      archiveEntries: "#/artifactory"

pipelines:
  - name: pipelines_FileSpec_3
    steps:
      - name: step_FileSpec_3
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: FileSpec_3
        execution:
          onExecute:
            - write-output "executing step..."
