resources:
  - name: artifact_1
    type: Artifact
    configuration:
      jfrogPlatformProvider: tokenIntegration        # JFrog Platform Access Token integration
      repositories:
        - samples-example-repo-local
      artifactPath:
        include:
          - tools/*
        exclude:
          - tools/exclude/*
      buildOn:
        deployed: true
        cached: true
        deleted: true
      branches:
        include: master
  - name: artifact_2
    type: Artifact
    configuration:
      jfrogPlatformProvider: tokenIntegration        # JFrog Platform Access Token integration
      repositories:
        - samples-example-repo-local
      artifactPath:
        include:
          - default/*
          - tools/*
      buildOn:
        deployed: true
      branches:
        include: artifactResource

pipelines:
  - name: artifact_resource_pipe_1
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: artifact_1
        execution:
          onExecute:
            - echo "executing step_1"
  - name: artifact_resource_pipe_2
    steps:
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: artifact_2
        execution:
          onExecute:
            - echo "executing step_1"
            - echo "sync started"
