resources:
  - name: artifact_res_1
    type: Artifact
    configuration:
      jfrogPlatformProvider: tokenIntegration        # required; JFrog Platform Access Token integration
      repositories:                                  # required
        - samples-example-repo-local
      artifactPath:                                  # required
        include:
          - tools/*
        exclude:
          - tools/exclude/*
      buildOn:                                       # required
        deployed: true
        cached: true
        deleted: true
      branches:                                      # required
        include: master                              # required
  - name: artifact_res_2
    type: Artifact
    configuration:
      jfrogPlatformProvider: tokenIntegration        # JFrog Platform Access Token integration
      repositories:
        - samples-example-repo-local
      artifactPath:
        include:
          - default/*
          - tools/*
      buildOn:
        deployed: true
      branches:
        include: artifactResource

pipelines:
  - name: artifact_resource_pipe_1
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: artifact_res_1
        execution:
          onExecute:
            - echo "executing step_1"
  - name: artifact_resource_pipe_2
    steps:
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: artifact_res_2
        execution:
          onExecute:
            - echo "executing step_2"
            - echo "sync started"
            - update_run_description "Triggered on event_type $res_pipeline_trigger_event_type in artifact_path $res_pipeline_trigger_event_path"
