resources:
  - name: artifact_res
    type: Artifact
    configuration:
      jfrogPlatformProvider: tokenIntegration        # required; JFrog Platform Access Token integration
      repositories:                                  # required
        - samples-example-repo-local
      artifactPath:                                  # optional
        include:
          - tools/*
        exclude:
          - tools/exclude/*
      buildOn:                                       # required
        deployed: true
        cached: true
        deleted: true
        copied: true
        moved: true      
      branches:                                      # required
        include: master                              # required

pipelines:
  - name: artifact_resource_pipe_1
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: artifact_res
        execution:
          onExecute:
            - echo "executing step_1"
            - update_run_description "Triggered on event_type $res_artifact_res_event_type in artifact_path $res_artifact_res_event_path"
