resources:
  - name: S_WF_012_resource
    type: PropertyBag
    configuration:
      runNumber: 0

pipelines:
  - name: pipeline_S_WF_012_001
    steps:
      - name: S_WF_012_input1
        type: Bash
        configuration:
          outputResources:
            - name: S_WF_012_resource
        execution:
          onExecute:
            - echo "test"
      - name: S_WF_012_step1
        type: Bash
        configuration:
          inputResources:
            - name: S_WF_012_resource
              newVersionOnly: true
        execution:
          onExecute:
            - echo "test"
      - name: S_WF_012_step2
        type: Bash
        configuration:
          inputResources:
            - name: S_WF_012_resource
        execution:
          onExecute:
            - echo "test"
